<?php
 echo  	"<section id=\"global-cta\" class=\"bc-feature-component bc-feature-component bc-cta-feature has-high-chroma\">"; 
 echo  	"	<div class=\"bc-elipses\">"; 
 echo  	"		<svg class=\"bc-elipses__svg\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 500 280\">"; 
 echo  	"			<title>Elipses</title>";
 echo  	"			<!-- fill:url(#linear-gradient) -->";
 echo  	"			<circle class=\"bc-elipses__elipse\" />"; 
 echo  	"			<circle class=\"bc-elipses__elipse\" />"; 
 echo  	"			<circle class=\"bc-elipses__elipse\" />";
 echo  	"			<circle class=\"bc-elipses__elipse\" />"; 
 echo  	"			<circle class=\"bc-elipses__elipse\" />"; 
 echo  	"		</svg>";
 echo  	"	</div> ";
 echo  	"	<article class=\"bc-feature-component__content\">";
 echo  	"		<div class=\"bc-feature-component__content__text-content\">";
 echo  	"		<p class=\"bc-content-label\">";
 echo  	"			<svg class=\"bc-svg-icon bc-svg-icon--admissions\">";
 echo  	"				<use xlink:href=\"./media/svg/icons/bc-svgs.svg#admissions-icon\"></use>"; 
 echo  	"			</svg>";
 echo  	"			Admissions";
 echo  	"		</p>"; 
 echo  	"		<h1 class=\"bc-feature-component__heading\">Getting started at ISD";
 echo  	"			<svg class=\"bc-svg-icon isd-cta-arrow\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 340.2 99\">";
 echo  	"				<title>Getting started at ISD</title> ";
 echo  	"				<circle class=\"isd-cta-arrow__circle\" cx=\"290.7\" cy=\"49.5\" r=\"48\"/>";
 echo  	"				<line class=\"isd-cta-arrow__line\" y1=\"49.39\" x2=\"265.98\" y2=\"49.39\"/>";
 echo  	"				<path class=\"isd-cta-arrow__carat\" d=\"M302,49.91,279.7,27.6l2.87-2.82L307.7,49.91,282.57,75l-2.82-2.82Z\" transform=\"translate(0 -1.5)\"/>";
 echo  	"			</svg>";
 echo  	"		</h1>";
 echo  	"		<p class=\"bc-feature-component__intro\">If you feel ISD is a right fit for your family, make an expression of interest to begin communication with our Admissions team.</p>";
 echo  	"		<p>Express your interest here:</p>";
 echo  	"		</div>";
 echo  	"	</article>";
 echo  	"	<div class=\"bc-feature-component__cta\">"; 
 echo  	"		<div class=\"bc-feature-component__content__text-content\">";
 echo  	"			<p>";
 echo		"				<b>";
 echo		"					<a class=\"bc-icon-link--featured\" href=\"https://docs.google.com/forms/d/19N_bz_sMx1yy0TEWD0qamubdOROFOiqDtOSdhC9AuaY/edit\">Pre-enrolment 2020 - 2021";
 echo  	"						<svg class=\"bc-svg-icon\">";
 echo  	"							<use xlink:href=\"./media/svg/icons/bc-svgs.svg#arrow\"></use>"; 
 echo  	"						</svg>";
 echo  	"					</a></b>";
 echo  	"				</b>";
 echo  	"			</p>";
 echo  	"			<p>";
 echo		"				<b>";
 echo		"					<a class=\"bc-icon-link--featured\" href=\"https://docs.google.com/a/internationalschooldublin.ie/forms/d/1vQdv9Tbh7zk2pkZXY_6PbyATVMQsahwSwmopeuO1LJ0/edit?usp=forms_home&ths=true\">Pre-enrolment 2021 - 2022";
 echo  	"						<svg class=\"bc-svg-icon\">";
 echo  	"							<use xlink:href=\"./media/svg/icons/bc-svgs.svg#arrow\"></use>"; 
 echo  	"						</svg>";
 echo  	"					</a></b>";
 echo  	"				</b>";
 echo  	"			</p>";
 
 echo  	"		</div>";
 echo  	"	</div>";
 echo  	"</section><!-- // .bc-cta-component -->";
?>