<?php
 echo "<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->";
 echo "<svg version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 0 0\" class=\"bc-svg-defs\" xml:space=\"preserve\">";
 echo "	<defs>";
 echo "		<linearGradient id=\"isd-rainbow-grad\" gradientUnits=\"userSpaceOnUse\" x1=\"0\" y1=\"25.5\" x2=\"1440\" y2=\"25.5\">";
 echo "			<stop  offset=\"0\" style=\"stop-color:#05D1D1\"/>";
 echo "			<stop  offset=\"0.25\" style=\"stop-color:#6881DB\"/>";
 echo "			<stop  offset=\"0.5\" style=\"stop-color:#D02CE5\"/>";
 echo "			<stop  offset=\"0.75\" style=\"stop-color:#F2EF11\"/>";
 echo "			<stop  offset=\"1\" style=\"stop-color:#3B857E\"/>";
 echo "		</linearGradient>";
 echo "		<linearGradient id=\"linear-gradient\" class=\"bc-svg-defs__linear-gradient\" viewBox=\"0 0 100 100\" gradientTransform=\"rotate(135)\">";
 echo "			<stop offset=\"0%\" stop-opacity=\"1\"  class=\"bc-svg-defs__linear-gradient__col-stop1\"/>"; 
 echo "			<stop offset=\"72%\" stop-opacity=\"1\" class=\"bc-svg-defs__linear-gradient__col-stop2\"/>";
 echo "		</linearGradient>";
 echo "		<linearGradient id=\"linear-gradient--orange\" class=\"bc-svg-defs__linear-gradient--orange\" viewBox=\"0 0 100 100\" gradientTransform=\"rotate(135)\">";
 echo "			<stop offset=\"0%\" stop-opacity=\"1\"  class=\"bc-svg-defs__linear-gradient__col-stop1\"/>"; 
 echo "			<stop offset=\"72%\" stop-opacity=\"1\" class=\"bc-svg-defs__linear-gradient__col-stop2\"/>";
 echo "		</linearGradient>";
 echo "	</defs>";
 echo "</svg>";
 echo "<header class=\"bc-site-header is-overlay\">";
 echo "	<div class=\"bc-site-header__content\">";
 echo "		<div class=\"bc-site-header__logo\">";
 echo "			<a href=\"./\" title=\"ISD Homepage\">";
 echo "				<img src=\"media/isd-logo.png\" alt=\"International School of Dublin\" class=\"\">";
 echo "			</a>";
 echo "		</div>";
 echo "		<nav class=\"bc-main-navigation\">";
 echo "			<h1 class=\"bc-site-header__heading\">Welcome to International School of Dublin</h1>";
 echo "			<div class=\"bc-main-navigation__navs\">";
 echo "				<div class=\"bc-main-navigation__main-nav\">";
 echo "					<ul class=\"bc-main-navigation__links\">";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Teaching &amp; Learning</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Admissions</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">About the School</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Student experience</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Community</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">For Irish families</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Contact</a></li>";
 echo "					</ul>";
 echo "				</div>";
 echo "				<div class=\"bc-main-navigation__sub-navigation\"> ";
 echo "					<h3 class=\"bc-site-header__sub-sub-heading\">Quick links</h3>";
 echo "					<ul class=\"bc-main-navigation__links\">";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">School calendar</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">School bus</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Student experience</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Community</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">For Irish families</a></li>";
 echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Contact</a></li>";
 echo "					</ul>";
 echo "				</div>";
 echo "			</div>";
 echo "		</nav>";
 echo "		<div class=\"bc-main-navigation-toggle\">";
 echo "			<a class=\"menu-icon-wrap bc-navigation-toggle\" href=\"javascript:void(0)\">";
 echo "				<?xml version=\"1.0\" encoding=\"utf-8\"?>";
 echo "					<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->";
 echo "					<svg version=\"1.1\" class=\"bc-menu-icon \" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"  viewBox=\"0 0 100 100\" xml:space=\"preserve\">";
 echo "						<g class=\"bc-menu-icon__lines\">";
 echo "							<line class=\"bc-menu-icon__line bc-menu-icon__lines__line bc-menu-icon__lines__line--top\" x1=\"1\" y1=\"25\" x2=\"99\" y2=\"25\"/>";
 echo "							<line class=\"bc-menu-icon__line bc-menu-icon__lines__line bc-menu-icon__lines__line--middle\" x1=\"1\" y1=\"50\" x2=\"99\" y2=\"50\"/>";
 echo "							<line class=\"bc-menu-icon__line bc-menu-icon__lines__line bc-menu-icon__lines__line--bottom\" x1=\"1\" y1=\"75\" x2=\"99\" y2=\"75\"/>";						
 echo "						</g>";
 echo "						<g class=\"bc-menu-icon__active-lines\">";
 echo "							<line class=\"bc-menu-icon__line bc-menu-icon__lines__active-line bc-menu-icon__lines__active-line--first\" x1=\"-70\" y1=\"-70\" x2=\"0\" y2=\"0\"/>";
 echo "							<line class=\"bc-menu-icon__line bc-menu-icon__lines__active-line bc-menu-icon__lines__active-line--second\" x1=\"100\" y1=\"0\" x2=\"170\" y2=\"-70\"/>";
 echo "						</g>";
 echo "					</svg>";
 echo "				</a>";
 echo "		</div><!-- // .bc-main-navigation-toggle -->";
 echo "	</div>";
 echo "	<div class=\"bc-main-navigation__underlay\"></div>";
 echo "</header>";
?>