<?php
echo "<header class=\"bc-site-header is-overlay\">";
echo "	<div class=\"bc-site-header__content\">";
echo "		<div class=\"bc-site-header__logo\">";
echo "			<a href=\"./\" title=\"ISD Homepage\">";
echo "				<img src=\"media/isd-logo.png\" alt=\"International School of Dublin\" class=\"\">";
echo "			</a>";
echo "		</div>";
echo "		<nav class=\"bc-main-navigation\">";
echo "			<h1 class=\"bc-site-header__heading\">Welcome to International School of Dublin</h1>";
echo "			<div class=\"bc-main-navigation__navs\">";
echo "				<div class=\"bc-main-navigation__main-nav\">";
echo "					<ul class=\"bc-main-navigation__links\">";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Teaching &amp; Learning</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Admissions</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">About the School</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Student experience</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Community</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">For Irish families</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Contact</a></li>";
echo "					</ul>";
echo "				</div>";
echo "				<div class=\"bc-main-navigation__sub-navigation\"> ";
echo "					<h3 class=\"bc-site-header__sub-sub-heading\">Quick links</h3>";
echo "					<ul class=\"bc-main-navigation__links\">";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">School calendar</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">School bus</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Student experience</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Community</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">For Irish families</a></li>";
echo "						<li class=\"bc-main-navigation__item\"><a class=\"bc-main-navigation__item__link\" href=\"javascript:void(0)\">Contact</a></li>";
echo "					</ul>";
echo "				</div>";
echo "			</div>";
echo "		</nav>";
echo "		<div class=\"bc-main-navigation-toggle\">";
echo "			<a href=\"javascript:void(0)\" class=\"bc-navigation-toggle\">";
echo					'<?xml version="1.0" encoding="utf-8"?>';
echo "				<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->";
echo "					<svg version=\"1.1\" class=\"bc-menu-icon\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 100 100\" enable-background=\"new 0 0 100 100\" xml:space=\"preserve\">";
echo "						<line class=\"bc-menu-icon__icon__line bc-menu-icon__icon__line--top\" fill=\"none\" stroke=\"#000000\" stroke-width=\"6\" stroke-miterlimit=\"10\" x1=\"1\" y1=\"25\" x2=\"99\" y2=\"25\"/> ";
echo "						<line class=\"bc-menu-icon__icon__line bc-menu-icon__icon__line--middle\" fill=\"none\" stroke=\"#000000\" stroke-width=\"6\" stroke-miterlimit=\"10\" x1=\"1\" y1=\"50\" x2=\"99\" y2=\"50\"/>";
echo "						<line class=\"bc-menu-icon__icon__line bc-menu-icon__icon__line--bottom\" fill=\"none\" stroke=\"#000000\" stroke-width=\"6\" stroke-miterlimit=\"10\" x1=\"1\" y1=\"77.5\" x2=\"99\" y2=\"77.5\"/>";
echo "				</svg>";
echo "			</a>";
echo "	</div><!-- // .bc-main-navigation-toggle -->";
echo "	</div>";
echo "	<div class=\"bc-main-navigation__underlay\"></div>";
echo "</header>";
?>